### ISSUE TITLE
How to Import Nodes?

### ISSUE THREAD

**Issue by olivernovakovic** [alaabenfatma/VisualSR#1]
Sorry for the dumb question:
How do I import the Nodes from nodes.dll to be used in the DEMO ?
Thanks

**Comment by olivernovakovic** [comment]
ok, I got it: you need to put the node.dll in the root folder next to demo.exe (not the .\Plugins folder)

**Comment by alaabenfatma** [comment]
Hi @olivernovakovic , glad you fixed your issue. I will be closing this Issue now.
